name = "Reckoner"
uuid = "bbd1d0f0-76cb-11ea-2afc-bb8485d7c580"
authors = ["Thalassocracy <42811940+Thalassocracy@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
